const { LangAr } = require('@bokata/lang-ar');
const { LangBn } = require('@bokata/lang-bn');
const { LangCa } = require('@bokata/lang-ca');
const { LangCs } = require('@bokata/lang-cs');
const { LangDa } = require('@bokata/lang-da');
const { LangDe } = require('@bokata/lang-de');
const { LangEl } = require('@bokata/lang-el');
const { LangEn } = require('@bokata/lang-en');
const { LangEs } = require('@bokata/lang-es');
const { LangEu } = require('@bokata/lang-eu');
const { LangFa } = require('@bokata/lang-fa');
const { LangFi } = require('@bokata/lang-fi');
const { LangFr } = require('@bokata/lang-fr');
const { LangGa } = require('@bokata/lang-ga');
const { LangGl } = require('@bokata/lang-gl');
const { LangHi } = require('@bokata/lang-hi');
const { LangHu } = require('@bokata/lang-hu');
const { LangHy } = require('@bokata/lang-hy');
const { LangId } = require('@bokata/lang-id');
const { LangIt } = require('@bokata/lang-it');
const { LangJa } = require('@bokata/lang-ja');
const { LangKo } = require('@bokata/lang-ko');
const { LangLt } = require('@bokata/lang-lt');
const { LangMs } = require('@bokata/lang-ms');
const { LangNe } = require('@bokata/lang-ne');
const { LangNl } = require('@bokata/lang-nl');
const { LangNo } = require('@bokata/lang-no');
const { LangPl } = require('@bokata/lang-pl');
const { LangPt } = require('@bokata/lang-pt');
const { LangRo } = require('@bokata/lang-ro');
const { LangRu } = require('@bokata/lang-ru');
const { LangSl } = require('@bokata/lang-sl');
const { LangSr } = require('@bokata/lang-sr');
const { LangSv } = require('@bokata/lang-sv');
const { LangTa } = require('@bokata/lang-ta');
const { LangTh } = require('@bokata/lang-th');
const { LangTl } = require('@bokata/lang-tl');
const { LangTr } = require('@bokata/lang-tr');
const { LangUk } = require('@bokata/lang-uk');
const { LangZh } = require('@bokata/lang-zh');

class LangAll {
  register(container) {
    container.use(LangAr);
    container.use(LangBn);
    container.use(LangCa);
    container.use(LangCs);
    container.use(LangDa);
    container.use(LangDe);
    container.use(LangEl);
    container.use(LangEn);
    container.use(LangEs);
    container.use(LangEu);
    container.use(LangFa);
    container.use(LangFi);
    container.use(LangFr);
    container.use(LangGa);
    container.use(LangGl);
    container.use(LangHi);
    container.use(LangHu);
    container.use(LangHy);
    container.use(LangId);
    container.use(LangIt);
    container.use(LangJa);
    container.use(LangKo);
    container.use(LangLt);
    container.use(LangMs);
    container.use(LangNe);
    container.use(LangNl);
    container.use(LangNo);
    container.use(LangPl);
    container.use(LangPt);
    container.use(LangRo);
    container.use(LangRu);
    container.use(LangSl);
    container.use(LangSr);
    container.use(LangSv);
    container.use(LangTa);
    container.use(LangTh);
    container.use(LangTl);
    container.use(LangTr);
    container.use(LangUk);
    container.use(LangZh);
  }
}

module.exports = LangAll;
