const { ConsoleConnector } = require('@bokata/console-connector');
const {
  Among,
  ArrToObj,
  BaseStemmer,
  containerBootstrap,
  Clonable,
  Container,
  defaultContainer,
  hasUnicode,
  unicodeToArray,
  asciiToArray,
  stringToArray,
  compareWildcars,
  getAbsolutePath,
  listFiles,
  listFilesAbsolute,
  loadEnv,
  Normalizer,
  ObjToArr,
  Stemmer,
  Stopwords,
  Tokenizer,
  Timer,
  MemoryStorage,
  uuid,
  dock,
  Context,
  dockStart,
} = require('@bokata/core-loader');
const { Evaluator, compile, Template, JavascriptCompiler } = require('@bokata/evaluator');
const { LangEn, StemmerEn, StopwordsEn, TokenizerEn, NormalizerEn, SentimentEn } = require('@bokata/lang-en');
const { logger } = require('@bokata/logger');
const { Nlp } = require('@bokata/nlp');

module.exports = {
  ConsoleConnector,
  Among,
  ArrToObj,
  BaseStemmer,
  containerBootstrap,
  Clonable,
  Container,
  defaultContainer,
  hasUnicode,
  unicodeToArray,
  asciiToArray,
  stringToArray,
  compareWildcars,
  getAbsolutePath,
  listFiles,
  listFilesAbsolute,
  loadEnv,
  Normalizer,
  ObjToArr,
  Stemmer,
  Stopwords,
  Tokenizer,
  Timer,
  MemoryStorage,
  uuid,
  dock,
  Context,
  dockStart,
  Evaluator,
  compile,
  Template,
  JavascriptCompiler,
  LangEn,
  StemmerEn,
  StopwordsEn,
  TokenizerEn,
  NormalizerEn,
  SentimentEn,
  logger,
  Nlp,
};
